# Testes de software

#### Requisitos para realização do teste:

- Aparelho desktop ou mobile com acesso à internet
- Site publicado na Internet
- Navegador de Internet - Preferencialmente, Chrome, Edge ou Firefox

###### Os testes a seguir tem como finalidade testar o funcionamento dos principais requisitos funcionais do projeto <br>

## Funcionalidade de Login do Sistema

| # | Cenário                    | Requisito Funcional | Ações                                                                                                                                                                                                    | Resultados Esperados                                                                                                                                                                                                              |
|---|----------------------------|---------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1 | Registro de usuário OK     | RF-00               | ⦁	Clicar no botão de Inscreva-se  ⦁	Informar os dados de usuário conforme orientações da tela  ⦁	Confirmar o registro do usuário  ⦁	Efetuar o login com as informações registradas                           | ⦁	Os dados do usuário devem ser registrados no Local Storage  ⦁	Usuário encaminhado para página principal  ⦁	Após a confirmação de cadastro, o sistema deve apresentar uma tela informando que o usuário foi cadastrado com sucesso. |
| 2 | Registro de usuário NÂO OK | RF-00               | ⦁	Clicar no botão de Inscreva-se  ⦁	Informar os dados de usuário, mas não informar senhas e e-mail  ⦁	Confirmar o registro do usuário                                                                       | ⦁	Após a confirmação de cadastro,  o sistema deve apresentar uma tela de erro informando que é obrigatório informar no mínimo, senhas e e-mail para a realização do cadastro.                                                      |
| 3 | Registro de usuário NÂO OK | RF-00               | ⦁	Clicar no botão de Inscreva-se  ⦁	Informar os dados de usuário conforme orientações da tela  ⦁	Informar senhas diferentes nos campos “senha” e “Insira senha novamente”  ⦁	Confirmar o registro do usuário | ⦁	Após a confirmação de cadastro,  o sistema deve apresentar uma tela de erro informando que as senhas informadas não conferem.                                                                                                    |
| 4 | Login OK                   | RF-00               | ⦁	Acessar opção de login popup  ⦁	Informar um login e senha corretos  ⦁	Confirmar a validação  ⦁	Aguardar o resultado                                                                                        | ⦁	Os dados do usuário corrente devem ser registrados no Session Storage  ⦁	Após a confirmação de login, o sistema deverá direcionar o usuário para uma página inicial de usuário logado.                                            |
| 5 | Login NÂO OK               | RF-00               | ⦁	Acessar tela de login  ⦁	Informar login e/ou senha incorretos  ⦁	Confirmar a validação  ⦁	Aguardar o resultado                                                                                             | ⦁	Após a confirmação de login, o sistema deve apresentar uma tela informando que a senha do usuário está incorreta.                                                                                                                |
| 6 | Login NÂO OK               | RF-00               | ⦁	Acessar tela de login  ⦁	Deixar campos de login e/ou senha em branco  ⦁	Confirmar a validação  ⦁	Aguardar o resultado                                                                                      | ⦁	Após a confirmação de login, o sistema deve apresentar uma tela informando que as senhas informadas não conferem.                                                                                                                |
| 7 | Controle de Sessão         | RF-00               | ⦁	Efetuar o login de um usuário cadastrado  ⦁	Acessar as outras páginas da plataforma  ⦁	Atualizar a página via refresh do browser (F5)                                                                     | ⦁        A página deve apresentar o nome do usuário logado logo após o processo de login e também após o refresh da página, além disso, a página também deve mostrar uma opção de logout.                                         |
| 8 | Logout                     | RF-00               | ⦁	Efetuar o login de um usuário cadastrado  ⦁	Acessar opção de logout em qualquer uma das páginas                                                                                                          | ⦁	Os dados do usuário corrente devem ser retirados no Session Storage  ⦁	Após a confirmação do logout, o sistema deve deslogar o usuário da plataforma e retornar para a página principal.                                          |
