-- MySQL Script generated by MySQL Workbench
-- Thu Apr  7 20:48:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ID` INT NOT NULL,
  `Username` VARCHAR(100) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` CHAR(11) NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Genero` CHAR(1) NULL,
  `DataNasc` DATETIME NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Papel` CHAR(1) NOT NULL,
  `Experiencia` INT NULL,
  `Descricao` TEXT(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `ID` INT NOT NULL,
  `Username` VARCHAR(100) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` CHAR(11) NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Genero` CHAR(1) NULL,
  `DataNasc` DATETIME NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Papel` CHAR(1) NOT NULL,
  `Descricao` TEXT(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leciona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Leciona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Leciona` (
  `Professor_ID` INT NOT NULL,
  `Aluno_ID` INT NOT NULL,
  `ID` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Valor` DECIMAL(2) NULL,
  PRIMARY KEY (`Professor_ID`, `Aluno_ID`, `ID`),
  INDEX `fk_Professor_has_Aluno_Aluno1_idx` (`Aluno_ID` ASC) VISIBLE,
  INDEX `fk_Professor_has_Aluno_Professor_idx` (`Professor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Aluno_Professor`
    FOREIGN KEY (`Professor_ID`)
    REFERENCES `mydb`.`Professor` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Professor_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_ID`)
    REFERENCES `mydb`.`Aluno` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materias` (
  `Sigla` CHAR(5) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Leciona_ID` INT NOT NULL,
  PRIMARY KEY (`Sigla`, `Leciona_ID`),
  INDEX `fk_Materias_Leciona1_idx` (`Leciona_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Materias_Leciona1`
    FOREIGN KEY (`Leciona_ID`)
    REFERENCES `mydb`.`Leciona` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Horarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Horarios` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Leciona_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Leciona_ID`),
  INDEX `fk_Horarios_Leciona1_idx` (`Leciona_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Horarios_Leciona1`
    FOREIGN KEY (`Leciona_ID`)
    REFERENCES `mydb`.`Leciona` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avalia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Avalia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Avalia` (
  `Professor_ID` INT NOT NULL,
  `Aluno_ID` INT NOT NULL,
  `Avaliacao` INT NULL DEFAULT 5,
  PRIMARY KEY (`Professor_ID`, `Aluno_ID`),
  INDEX `fk_Professor_has_Aluno_Aluno2_idx` (`Aluno_ID` ASC) VISIBLE,
  INDEX `fk_Professor_has_Aluno_Professor1_idx` (`Professor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Aluno_Professor1`
    FOREIGN KEY (`Professor_ID`)
    REFERENCES `mydb`.`Professor` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Professor_has_Aluno_Aluno2`
    FOREIGN KEY (`Aluno_ID`)
    REFERENCES `mydb`.`Aluno` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `Sigla` CHAR(5) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ensina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ensina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ensina` (
  `Professor_ID` INT NOT NULL,
  `Materia_Sigla` CHAR(5) NOT NULL,
  PRIMARY KEY (`Professor_ID`, `Materia_Sigla`),
  INDEX `fk_Professor_has_Materia_Materia1_idx` (`Materia_Sigla` ASC) VISIBLE,
  INDEX `fk_Professor_has_Materia_Professor1_idx` (`Professor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Materia_Professor1`
    FOREIGN KEY (`Professor_ID`)
    REFERENCES `mydb`.`Professor` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Professor_has_Materia_Materia1`
    FOREIGN KEY (`Materia_Sigla`)
    REFERENCES `mydb`.`Materia` (`Sigla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estuda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estuda` (
  `Materia_Sigla` CHAR(5) NOT NULL,
  `Aluno_ID` INT NOT NULL,
  PRIMARY KEY (`Materia_Sigla`, `Aluno_ID`),
  INDEX `fk_Materia_has_Aluno_Aluno1_idx` (`Aluno_ID` ASC) VISIBLE,
  INDEX `fk_Materia_has_Aluno_Materia1_idx` (`Materia_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_has_Aluno_Materia1`
    FOREIGN KEY (`Materia_Sigla`)
    REFERENCES `mydb`.`Materia` (`Sigla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Materia_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_ID`)
    REFERENCES `mydb`.`Aluno` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
